### ISSUE TITLE
Ellipse nodes aren't expanded

### ISSUE THREAD

**Issue by superbobry** [iVis-at-Bilkent/cytoscape.js-expand-collapse#10]
To reproduce add the following style:

```js
{
    selector: "[expanded-collapsed='collapsed']",
    style: {
        "background-color": "darkblue",
        "shape": "ellipse",
        "width": 100,
    }
}
```

**Comment by ugurdogrusoz** [comment]
Looks like this is because we draw the expand-collapse cues at the upper left corner, which happens to be outside node boundaries in case of ellipses! If you must use ellipses, you might want to consider putting these cues inside the node. 

@metincansiper @mrsfy Can one position these ques say "towards" upper left (a certain offset away from upper left) using published API of this extension?

**Comment by metincansiper** [comment]
Yes there is 'expandCollapseCuePosition' option for this purpose. However, I realized that this feature was buggy and I fixed the related bug. It must be working well in version '1.1.2'. 

For example if you want the cues to be rendered at the node centers it can be used in the following way:

      expandCollapseCuePosition: function(ele) {
            return ele.position()
      }

**Comment by ugurdogrusoz** [comment]
In that case, I consider this issue invalid.
