### ISSUE TITLE
Collapsed children are not in graph

### ISSUE THREAD

**Issue by sashokbg** [iVis-at-Bilkent/cytoscape.js-expand-collapse#126]
Hello,

I am developing a feature where I have to locate a node on the graph and when my node is a part of a collapsed node the following query does not return anything:

cy.getElementById('my-node');

When I expand the node and the children become visible, the above code returns my object.

Is there a way to search within collapsed nodes' children ?

Thank you

**Comment by hasanbalci** [comment]
@sashokbg You can use one of the API functions such as `api.getCollapsedChildren(node)`, `api.getCollapsedChildrenRecursively(node)` or `api.getAllCollapsedChildrenRecursively()`. See [README.md](https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/blob/master/README.md) for more details.

**Comment by sashokbg** [comment]
Hello @hasanbalci thank you for your prompt response it worked correctly !

For the curious here is what I, as you suggested:

api.getAllCollapsedChildrenRecursively().filter('node[id = "my-node"]')

--

I was thinking, wouldn't it be possible to just hide collapsed nodes' children instead of removing them from the graph ?
This way all basic operations like cy.$() will still function.

**Comment by hasanbalci** [comment]
Hi @sashokbg, I'm glad that it solved your problem. For your suggestion, you can see [this discussion](https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/issues/57) and especially the [answer](https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/issues/57#issuecomment-369639109) of @ugurdogrusoz. Because the main purpose of the extension is to manage complexity, we prefer removing elements from the graph so that the number of elements to be dealt with become less.

**Comment by sashokbg** [comment]
Thank you once again, I will check the discussion !
