### ISSUE TITLE
Performance 

### ISSUE THREAD

**Issue by superbobry** [iVis-at-Bilkent/cytoscape.js-expand-collapse#13]
I've noticed that calling `cy.collapseAll` on a graph (250 nodes, 70 edges) takes almost twice as long as computing the layout/rendering. I don't quite understand the machinery behind `expand-collapse`, but I wonder if there's been any benchmarks to evaluate its performance?

**Update**: I did some profiling and it seems the longest operation is [`eles.move`](http://js.cytoscape.org/#collection/graph-manipulation/eles.move), which accounts for ~40% of total time.

![image](https://cloud.githubusercontent.com/assets/185856/17816238/ddc072ba-6640-11e6-880a-3556d3bca989.png)

**Comment by superbobry** [comment]
Adding `cy.batch` to `collapseBottomUp` and `expandTopDown` improved the running time quite a bit. I understand that this isn't an option if animation is enabled, but otherwise it looks like a worthy special case.

**Comment by metincansiper** [comment]
@superbobry Thanks for your help, the performance of related operations seems to be increased. I Added 'cy.batch()' to 'collapseBottomUp()' in collapse operation there is no animation other than end layout, so there is no problem related to animation.

For expand case I added 'cy.batch()' to 'simpleExpandNode()' with the condition of animate parameter is false. This should work for expand all as well because for 'expandAll()' this parameter is always false (Animation can be performed if only one node is being expanded).

I am aware of that the things related to animate seems complex and not readable in code, so what I wrote above may note make sense to you. I am sorry for this but for some reasons the readability and understandability of code is reduced while we are struggling with adding animation feature to this extension.

You can see my commit attached to this issue. If there is no problem now we can close this issue.
