### ISSUE TITLE
tabs issue , need to call sizeCanvas()

### ISSUE THREAD

**Issue by mafar** [iVis-at-Bilkent/cytoscape.js-expand-collapse#23]
I am using layouts and inside layouts are tabs , each tab has cytoscape js  with expand collapse.
From what I have fiigured, I need to manually call internal``` sizeCanvas()``` of expand-collapse afetr tab shown or layout resized sicne my buttons hide after window resize or layout resize.

I tried calling ```cy.expandCollapse( ); // without options``` on tab shown or layout resized hoping it will fix that. expand cues do appear but they make an extra canvas.

It will be very helpful if to call ```resize();``` on expandCollapse like ```cy.expandCollapseResize( );```

Problem is canvas resizing is bound with window and it resizes it before layouts are resized.so once layouts are resized, expandCollapse canvas is already resized and defaults to 100,100 width height.

**Comment by djangosdk** [comment]
Above PR fixed all our issues.

**Comment by metincansiper** [comment]
@maxkfranz I think that it seems logical to listen ```cy.on('resize', function(){``` instead of  ```$(window).bind('resize', function () {``` as @djangosdk and @abeersaqib suggested, because  ```cy.resize() ``` is automatically called for you on the window‘s resize event as stated here (http://js.cytoscape.org/#cy.resize). However, as far as I see other cytoscape extensions as well listen windows resize event (they do not listen  ```cy.on('resize', function(){```) is there a special reson for this. Do you foresee any inconvenience of listening ```cy.on('resize', function(){``` on this extension instead of windows resize event?

**Comment by djangosdk** [comment]
Hi
Most porbably cytoscape-edge-handles extension resize is bound to ``` cy.on('resize', function(){``` because it also introduces extra canvas and its controls must be resized after cy is resized. 
The order is important IMO. ( resize extra canvases other than cy-canvas after cy is resized)
With ``$(window).bind('resize', function () {``` , the order is lost.

**Comment by maxkfranz** [comment]
It should be fine, though the event is currently undocumented...

https://github.com/cytoscape/cytoscape.js/issues/1665

**Comment by maxkfranz** [comment]
Not sufficient.  The event is undocumented, because it's not really useful unless you want to know when `cy.resize()` was called directly by the dev's code.

**Comment by maxkfranz** [comment]
Until 3.1, relying on an internal `resize` event won't work.  Some extensions listen to `resize` only for when the dev calls `cy.resize()` himself (because Cytoscape can't detect all cases of when a resize would be necessary due to limitations in the browser).  I think the approach that extensions like edgehandles takes is to resize at the beginning of a gesture just before anything needs to be drawn.  That way, you avoid resizing on each frame (expensive) and stay up-to-date.

**Comment by ugurdogrusoz** [comment]
@metincansiper is this obsolete? should we close?

**Comment by metincansiper** [comment]
@maxkfranz as far as I see in the latest version of cytoscape.js  ```cy.on('resize', function(){```  is called when ever window is resized. Can we listen to ```cy.on('resize', function(){``` instead of  ```$(window).bind('resize', function () {``` now?

**Comment by ugurdogrusoz** [comment]
@maxkfranz Could you please answer @metincansiper 's question?

**Comment by maxkfranz** [comment]
[You can use `resize` in cytoscape>=3.1](https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/issues/23#issuecomment-270978662).  It should detect window resizes and most resizes of the div -- thought it's not possible to detect all.

**Comment by manotoor** [comment]
Having this issue when calling, cy.resize(), my canvas for expand collapse is not being updated. Is there a way to explicitly call it with expand collapse api?

**Comment by metincansiper** [comment]
@manotoor @mafar Does your problem remains when you use this extension from ``resize-fix`` branch (#89).

**Comment by hasanbalci** [comment]
This must be solved with #89, so I'm closing. Open again if you see any problem.
