### ISSUE TITLE
Expose repairEdges

### ISSUE THREAD

**Issue by pcurrivan** [iVis-at-Bilkent/cytoscape.js-expand-collapse#50]
In an app using remove() and restore(), meta edges can be saved and restored (along with their connectedNodes)  The user needs to be able to call repairEdges to fix meta edges after they are restored.

**Comment by kinimesi** [comment]
@pcurrivan What do you mean by *fixing meta edges*? Can you explain how do you save and restore meta edges and their connected nodes?

**Comment by pcurrivan** [comment]
Here's an example:
Vertices: {A,B,b}
Edge: {A,b}
Assume B is the parent of b.

Do the following operations:
collapse B
remove A
expand B
restore A

When A is removed, is has a connected meta edge {A,B}, which is restored when A is restored.  But b is in the graph, so the meta edge {A,B} needs to be fixed/repaired to become {A,b} again.

By the way, there are other snags when using remove() and restore() with this extension (e.g. restoring an element whose parent (or parent of an endpoint in the case of edges) is collapsed).  We have handled many of these cases in our app, but we are considering giving up and just using "invisibility" rather than "hiding" (using the terms from Prof. Dogrusoz's paper).  Do you have any general thoughts about the feasibility of using remove() and restore() with this extension?

**Comment by kinimesi** [comment]
@pcurrivan `repairEdges` is meant for internal use only. If you like, you can copy `repairEdges` function and use it.

Instead of removing nodes, I would suggest you to make them `invisible` by setting `display` property in CSS to `none`. For restoring nodes, you will need to set `display` property to `element`. If you do it like this, then all meta-edges (including invisible ones) will be repaired when the node is expanded. So you won't face the same problem.

P.S: you can use `:visible` selector to match elements that are visible.

**Comment by pcurrivan** [comment]
display:none seems to work quite well.  thanks!

**Comment by kinimesi** [comment]
Since your problem is solved, closing.
