### ISSUE TITLE
Can expand-collapse be used on touch screens?

### ISSUE THREAD

**Issue by atabakhafeez** [iVis-at-Bilkent/cytoscape.js-expand-collapse#53]
Firstly, thanks for the library. It has been very helpful till now for our use case.

I wanted to know if there is a way to use the library for touch screens. For now, it seems that you only see the expand-collapse cue on mouse hover. Is there any other way that could also be used for touch screens using this library? If not, is there any chance that it will be added soon?

**Comment by kinimesi** [comment]
@atabakhafeez One way of using this extension on touchscreen devices is to listen for specific events and call expand/collapse functions when that event occurs. 
1. Listen for `cxttap` (two finger tap event) or `doubletap` event.
2. If node is collapsible call `api.collapse` function, else if node is expandable call `api.expand` function.

Note: you will need to implement double tap event yourself. It is not provided by Cytoscape.js For a sample implementation [see this](https://github.com/iVis-at-Bilkent/newt/blob/357bb2403555ab652643217adc0be5ca4fc9d540/app/js/app-cy.js#L800).

**Comment by ugurdogrusoz** [comment]
@atabakhafeez Since expand-collapse extension provides its functionality through an API, you could easily implement a button or menu item which expands/collapses the *selected* compound node using the API. We plan to change the way visual cues are shown in the future as well. Rather than mouse over, we'll display visual cues for expand/collapse when node is selected.
