### ISSUE TITLE
Canvas blocks navigator extension's container HTML element

### ISSUE THREAD

**Issue by canbax** [iVis-at-Bilkent/cytoscape.js-expand-collapse#80]
This extension adds a canvas element on run-time with [this line](https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/blob/master/src/cueUtilities.js#L18)

[Navigator extension](https://github.com/cytoscape/cytoscape.js-navigator) also uses a `div` element to show an overview. Since the canvas blocks UI, the navigator element doesn't catch any click events.
![2019-07-23_10-57-31](https://user-images.githubusercontent.com/8426741/61693909-10e9a700-ad39-11e9-993e-b9cdaf2bbba0.png)

**Comment by ugurdogrusoz** [comment]
I suspect some other extensions such as node-resize have the same issue.

**Comment by hasanbalci** [comment]
The problem is because of z-index values of canvases introduced by different extensions. Default z-index value for expand-collapse is 999, while it is 100 for navigator extension. Therefore, navigator is hidden behind the expand-collapse canvas.  

One generic solution for this problem may be to introduce a z-index value option for users if extension creates a new canvas. 

For the above specific case, however, assigning a z-index value that is greater than 999 for the navigator extension can solve the problem.
`$('.cytoscape-navigator-wrapper').css('z-index', 1000);`

**Comment by ugurdogrusoz** [comment]
This fixed worked! Could we please put a notice on this on README of this extension and **node-resize* extension?

**Comment by hasanbalci** [comment]
I added a notice on README about this.
