### ISSUE TITLE
Changed style is not applied to collapsed nodes

### ISSUE THREAD

**Issue by torman119** [iVis-at-Bilkent/cytoscape.js-expand-collapse#91]
We allow users to change the style of the whole graph (they can switch between different styles).
When we apply a new style to the graph via `"cy.style(style01)" `the new style is only applied to the visible nodes. If we then expand a node the nodes inside still use the previous style.
Current workaround we use is to apply the current style after nodes are expanded via
```
cy.nodes().on("expandcollapse.afterexpand", function (event) {
            cy.style(currentStyle);            
});
```
We tried with `cy.style().clear();` to reset the style but collapsed nodes still use old style.

**Comment by ugurdogrusoz** [comment]
@torman119 Does the described workaround not work? Or you're trying to get a cleaner solution?
Let me make sure we understand the problem here. You apply a new style to a graph where you have some collapsed compound nodes. When collapsed compounds are expanded, you expect the newly exposed child nodes/edges to have the new style but they don't?

**Comment by torman119** [comment]
@ugurdogrusoz The workaround works, and it solves the issue.
And you describe the problem correct: child nodes in a collapsed node use the previous style after a new style is applied to the whole graph. A scenario would be theming which changes the colors of the nodes.
My expecation would be that a new style for the whole graph is also applied to collapsed nodes but the workaround works, so it is a possible solution.

**Comment by hasanbalci** [comment]
The reason that the new style is not applied to child nodes is because extension temporarily removes the child nodes from the graph when a node is collapsed. In other words, the child nodes don't exist when the new style is applied. When the node is expanded, the child nodes are restored with their old styles. If the workaround works, then I think there is no problem.

**Comment by hasanbalci** [comment]
@torman119 As an option, you can also try to apply the new style to temporarily removed child nodes by reaching them via extension API:

`api.getAllCollapsedChildrenRecursively()` Get collapsed children of all collapsed nodes recursively. Returned value includes edges and nodes, use selector to get edges or nodes.
