### ISSUE TITLE
IE11 error

### ISSUE THREAD

**Issue by denglouhen** [iVis-at-Bilkent/cytoscape.js-expand-collapse#99]
I just use this extension in my Vue project.
My code is 
```
var expandCollapse = require("cytoscape-expand-collapse");
expandCollapse(cytoscape);
 .....
 _this.cy.expandCollapse(optionsExpand);
```

Then the IE11 throws an error 'TypeError: Object does not support "append" attribute or method
.....
 at module.exports (eval code:394:5)
   at Anonymous function (eval code:286:9)
   at Anonymous function (eval code:2219:9)
   at run (eval code:75:13)
   at Anonymous function (eval code:92:30)
   at flush (eval code:18:9)",
      Symbol()_n.a7vurm6t6lx: undefined,
      Symbol()_o.a7vurm6t6lx: undefined,
      Symbol(react.element)_m.a7vurm6t6lx: undefined'.

I removed the '_this.cy.expandCollapse(optionsExpand)' the error is disappered.
I want to check whether the demo is working in IE11 but I get a blank page.

So is the current extesion compatible with IE11?

**Comment by denglouhen** [comment]
"cytoscape": "^3.14.1",
 "cytoscape-expand-collapse": "^3.2.0"

**Comment by hasanbalci** [comment]
Apparently, there are some code snippets in the extension that aren't supported by IE11 including "append" method. Hence, it's currently not compatible with IE11.

**Comment by msalihaltun** [comment]
I was able to solve the problem with `append` method by using `appendChild` method in its place since it was appending only one element. 

Solving this problem revealed some other issues though. IE11 lacks support (at least) for [arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) and [`Array.from`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from) syntax as well which are used plenty in all i-Vis cytoscape extensions. 

I didn't go ahead with the change of `append` to `appendChild` thereafter.

**Comment by ugurdogrusoz** [comment]
OK, let's forget about IE 11, not a recent browser anyway.
